Fix scons file for arm64 and add mac instructions to readme
RevoluPowered/one-voip-godot-4 pull request #15
Opened 2024-02-20 07:12 UTC by marc-weber1

2024-03-07 17:44 UTC, cgodley commented on README.md
> +- [Mac] (#mac) ✅
There should not be a space here
```suggestion
- [Mac](#mac) ✅
```

2024-03-07 18:09 UTC, cgodley commented on README.md
> +In thirdparty/opus: `cmake -Bbuild -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"`
When I tested this on mac m1 Sonoma 14.3, I got the warning `ERRORRuntime cpu capability detection needed for MAY_HAVE_NEON`, and the `make` command failed during `Building C object CMakeFiles/opus.dir/celt/arm/celt_neon_intr.c.o`.

Might want to only build for the local machine (not universal) until that issue is resolved.

```suggestion
In thirdparty/opus: `cmake -Bbuild
```

2024-03-07 18:25 UTC, cgodley requested changes

2024-03-07 18:25 UTC, cgodley commented on README.md
> +In thirdparty/opus/build: `make` (?)
```suggestion
In thirdparty/opus/build: `make`
```

2024-03-07 18:25 UTC, cgodley commented on SConstruct
>      env.Append(CXXFLAGS = ['-fpermissive'])
I was able to successfully build and run without `-fpermissive` on mac m1 sonoma 14.3
```suggestion
    if env["platform"] != "macos":
        env.Append(CXXFLAGS = ['-fpermissive'])
```

2024-03-07 18:25 UTC, cgodley commented on README.md
> +Not sure on the status of whether unsigned GDExtensions can be loaded into MacOS, but it builds, so here are the instructions anyways
```suggestion
Not sure on the status of whether unsigned GDExtensions can be loaded into MacOS, but it builds, so here are the instructions anyways

You may need to set `driver/mix_rate=48000` in `project.godot`
```

2024-03-07 18:26 UTC, cgodley commented
Sorry for the wall of text, first time using GitHub code review feature

2024-03-09 04:29 UTC, marc-weber1 commented
tyty

2024-03-28 23:19 UTC, merged

2024-03-28 23:19 UTC, marc-weber1 commented
w.e I merged it just lmk if there are more changes and ill put them on directly